// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Widget from "../components/Widget.js";
import * as FavButton from "../components/FavButton.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as TranslateHook from "../hooks/TranslateHook.js";
import * as TranslateResult from "../components/TranslateResult.js";

function PopupApp(props) {
  var match = React.useState(function () {
        return "";
      });
  var setText = match[1];
  var text = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setSourceText = match$1[1];
  var sourceText = match$1[0];
  var textInput = React.useRef(null);
  var data = TranslateHook.useTranslate(sourceText);
  var setTextInputRef = function (element) {
    textInput.current = element;
  };
  var focusTextInput = function (param) {
    Belt_Option.forEach(Caml_option.nullable_to_opt(textInput.current), (function (input) {
            input.focus();
          }));
  };
  var handleTranslate = function (param) {
    if (text !== "") {
      return setSourceText(function (param) {
                  return text;
                });
    } else {
      return focusTextInput(undefined);
    }
  };
  var handleChange = function ($$event) {
    var value = $$event.target.value;
    setText(function (param) {
          return value;
        });
  };
  var handleKeyDown = function (evt) {
    var isCtrlKey = evt.ctrlKey;
    var key = evt.key;
    if (isCtrlKey && key === "Enter") {
      return setSourceText(function (param) {
                  return text;
                });
    }
    
  };
  React.useEffect((function () {
          focusTextInput(undefined);
        }), []);
  var tmp;
  tmp = typeof data === "number" || data.TAG !== /* TResult */0 ? null : React.createElement(FavButton.make, {
          text: sourceText,
          trans: data._0
        });
  var tmp$1;
  tmp$1 = typeof data === "number" ? null : (
      data.TAG === /* TResult */0 ? React.createElement(TranslateResult.make, {
              data: data._0,
              className: "text-sm"
            }) : (
          data._0 ? React.createElement(Widget.Loading.make, {
                  delay: 450
                }) : null
        )
    );
  return React.createElement("div", {
              className: "card card-compact w-56 bg-base-100 shadow-xl rounded-none"
            }, React.createElement("div", {
                  className: "bg-primary h-5 text-right"
                }, tmp), React.createElement("div", {
                  className: "card-body"
                }, React.createElement("textarea", {
                      ref: Caml_option.some(setTextInputRef),
                      className: "textarea textarea-primary leading-4 min-h-16 p-2",
                      placeholder: "please input...",
                      rows: 5,
                      value: text,
                      onKeyDown: handleKeyDown,
                      onChange: handleChange
                    }), React.createElement("button", {
                      className: "btn btn-primary btn-sm m-2",
                      onClick: handleTranslate
                    }, "Translate"), tmp$1));
}

var make = PopupApp;

export {
  make ,
}
/* react Not a pure module */
