// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as PopupApp from "./PopupApp.js";
import * as Client from "react-dom/client";

import '../common.css'
;

var rootElement = document.querySelector("#root");

if (!(rootElement == null)) {
  var root = Client.createRoot(rootElement);
  root.render(React.createElement(PopupApp.make, {}));
}

export {
  
}
/*  Not a pure module */
