// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as PopupApp from "./PopupApp.js";
import * as ReactDom from "react-dom";

import '../common.css'
;

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(PopupApp.make, {}), root);
}

export {
  
}
/*  Not a pure module */
