// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as TranslateResult from "../components/TranslateResult.js";

function PopupApp(Props) {
  var match = React.useState(function () {
        return /* Noop */2;
      });
  var setLoading = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var seErrText = match$1[1];
  var match$2 = React.useState(function () {
        return [];
      });
  var setResults = match$2[1];
  var match$3 = React.useState(function () {
        return "";
      });
  var setText = match$3[1];
  var text = match$3[0];
  var textInput = React.useRef(null);
  var setTextInputRef = function (element) {
    textInput.current = element;
  };
  var focusTextInput = function (param) {
    Belt_Option.forEach(Caml_option.nullable_to_opt(textInput.current), (function (input) {
            input.focus();
          }));
  };
  var handleChange = function ($$event) {
    var value = $$event.target.value;
    setText(function (param) {
          return value;
        });
  };
  var handleTranslate = function (param) {
    if (text !== "") {
      setLoading(function (_p) {
            return /* Yes */0;
          });
      seErrText(function (param) {
            return "";
          });
      chrome.runtime.sendMessage(text).then(function (ret) {
            if (ret.TAG === /* Ok */0) {
              var trans_result = ret._0;
              setResults(function (_p) {
                    return trans_result;
                  });
            } else {
              var msg = ret._0;
              seErrText(function (_p) {
                    return msg;
                  });
            }
            setLoading(function (_p) {
                  return /* No */1;
                });
          });
      return ;
    } else {
      return focusTextInput(undefined);
    }
  };
  var handleKeyDown = function (evt) {
    var isCtrlKey = evt.ctrlKey;
    var key = evt.key;
    if (isCtrlKey && key === "Enter") {
      return handleTranslate(undefined);
    }
    
  };
  React.useEffect((function () {
          focusTextInput(undefined);
        }), []);
  return React.createElement("div", {
              className: "card card-compact w-56 bg-base-100 shadow-xl"
            }, React.createElement("div", {
                  className: "card-body"
                }, React.createElement("textarea", {
                      ref: setTextInputRef,
                      className: "textarea textarea-primary leading-4 min-h-16",
                      placeholder: "please input...",
                      rows: 5,
                      value: text,
                      onKeyDown: handleKeyDown,
                      onChange: handleChange
                    }), React.createElement("button", {
                      className: "btn btn-primary btn-sm m-2",
                      onClick: handleTranslate
                    }, "Translate"), React.createElement(TranslateResult.make, {
                      loading: match[0],
                      errText: match$1[0],
                      results: match$2[0],
                      className: "text-secondary p-2 min-h-8"
                    })));
}

var make = PopupApp;

export {
  make ,
}
/* react Not a pure module */
