// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TranslateResult from "../components/TranslateResult.js";

function Favorite(Props) {
  var match = React.useState(function () {
        return [];
      });
  var setRecords = match[1];
  React.useEffect((function () {
          chrome.runtime.sendMessage({
                  _type: {
                    TAG: /* FAVORITE */1,
                    _0: /* GETALL */2
                  }
                }).then(function (ret) {
                setRecords(function (param) {
                      return ret;
                    });
              });
        }), []);
  var recordEles = match[0].map(function (v) {
        return React.createElement("div", {
                    className: "card card-compact w-80 bg-base-100 shadow-xl"
                  }, React.createElement("div", {
                        className: "card-body"
                      }, React.createElement("div", {
                            className: "border-b pb-1"
                          }, React.createElement("div", {
                                className: "flex justify-between"
                              }, React.createElement("span", undefined, new Date(v.date).toLocaleDateString()), React.createElement("a", {
                                    title: v.title,
                                    href: v.url,
                                    target: "_blank"
                                  }, React.createElement("img", {
                                        className: "w-5",
                                        src: v.favIconUrl
                                      }))), React.createElement("p", {
                                className: "font-bold text-xl line-clamp-1"
                              }, v.text)), React.createElement(TranslateResult.make, {
                            data: v.trans
                          })));
      });
  return React.createElement("div", {
              className: "flex flex-wrap gap-4"
            }, recordEles);
}

var make = Favorite;

export {
  make ,
}
/* react Not a pure module */
