// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$History(Props) {
  var match = React.useState(function () {
        return [];
      });
  var setRecords = match[1];
  React.useEffect((function () {
          chrome.runtime.sendMessage({
                  _type: {
                    TAG: /* HISTORY */0,
                    _0: /* GETALL */2
                  }
                }).then(function (ret) {
                setRecords(function (param) {
                      return ret;
                    });
              });
        }), []);
  var recordEles = match[0].map(function (v) {
        return React.createElement("div", {
                    className: "card card-compact bg-base-100 shadow-xl m-4"
                  }, React.createElement("div", {
                        className: "card-body"
                      }, React.createElement("div", {
                            className: "flex justify-between"
                          }, React.createElement("span", undefined, new Date(v.date).toLocaleString()), React.createElement("a", {
                                className: "inline-flex gap-2",
                                href: v.url,
                                target: "_blank"
                              }, React.createElement("span", undefined, v.title), React.createElement("img", {
                                    className: "w-5",
                                    src: v.favIconUrl
                                  }))), React.createElement("p", {
                            className: "font-bold text-xl"
                          }, v.text)));
      });
  return React.createElement("div", undefined, recordEles);
}

var make = $$History;

export {
  make ,
}
/* react Not a pure module */
