// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RecordHook from "../hooks/RecordHook.js";
import * as RecordAction from "./RecordAction.js";
import * as JsxRuntime from "react/jsx-runtime";

function $$History(props) {
  var match = RecordHook.useRecord("history");
  var onCheck = match.onCheck;
  var records = match.records;
  var recordEles = records.map(function (record) {
        var date = record.date;
        var checked = record.checked;
        var sync = record.sync;
        var boarderClass = checked ? "border-primary" : "";
        return JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsxs("div", {
                                          children: [
                                            JsxRuntime.jsx("span", {
                                                  children: new Date(date).toLocaleString()
                                                }),
                                            JsxRuntime.jsx("span", {
                                                  children: sync ? "sync" : "",
                                                  className: "ml-4"
                                                })
                                          ],
                                          className: "w-50"
                                        }),
                                    JsxRuntime.jsxs("a", {
                                          children: [
                                            JsxRuntime.jsx("span", {
                                                  children: record.title,
                                                  className: "line-clamp-1"
                                                }),
                                            JsxRuntime.jsx("img", {
                                                  className: "w-5",
                                                  src: record.favIconUrl
                                                })
                                          ],
                                          className: "inline-flex gap-2 flex-1 justify-end",
                                          href: record.url,
                                          target: "_blank"
                                        })
                                  ],
                                  className: "flex gap-2 justify-between"
                                }),
                            JsxRuntime.jsx("p", {
                                  children: record.text,
                                  className: "font-bold text-xl"
                                })
                          ],
                          className: "card-body"
                        }),
                    className: "card card-compact card-bordered cursor-pointer bg-base-100 shadow-xl " + boarderClass,
                    "data-testid": "historyItemWrap",
                    onClick: (function (param) {
                        onCheck(record);
                      })
                  }, date.toString());
      });
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(RecordAction.make, {
                      records: records.filter(function (v) {
                            return v.checked;
                          }),
                      onDelete: match.onDelete,
                      onSync: match.onSync,
                      onClear: match.onClear,
                      onSearch: match.onSearch,
                      onCancel: match.onCancel
                    }),
                JsxRuntime.jsx("div", {
                      children: recordEles,
                      className: "flex flex-col gap-y-4 p-5"
                    })
              ]
            });
}

var make = $$History;

export {
  make ,
}
/* RecordHook Not a pure module */
