// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RecordHook from "../hooks/RecordHook.js";
import * as RecordAction from "./RecordAction.js";

function $$History(Props) {
  var match = RecordHook.useRecord(/* HISTORY */0);
  var onCheck = match.onCheck;
  var records = match.records;
  var recordEles = records.map(function (v) {
        var date = v.date;
        var boarderClass = v.checked ? "border-primary" : "";
        return React.createElement("div", {
                    key: date.toString(),
                    className: "card card-compact card-bordered cursor-pointer bg-base-100 shadow-xl " + boarderClass + "",
                    onClick: (function (param) {
                        onCheck(v);
                      })
                  }, React.createElement("div", {
                        className: "card-body"
                      }, React.createElement("div", {
                            className: "flex justify-between"
                          }, React.createElement("span", undefined, new Date(date).toLocaleString()), React.createElement("a", {
                                className: "inline-flex gap-2",
                                href: v.url,
                                target: "_blank"
                              }, React.createElement("span", undefined, v.title), React.createElement("img", {
                                    className: "w-5",
                                    src: v.favIconUrl
                                  }))), React.createElement("p", {
                            className: "font-bold text-xl"
                          }, v.text)));
      });
  return React.createElement("div", undefined, React.createElement(RecordAction.make, {
                  className: "mb-4",
                  records: records.filter(function (v) {
                        return v.checked;
                      }),
                  onDelete: match.onDelete,
                  onClear: match.onClear,
                  onSearch: match.onSearch,
                  onCancel: match.onCancel
                }), React.createElement("div", {
                  className: "flex flex-col gap-y-4"
                }, recordEles));
}

var make = $$History;

export {
  make ,
}
/* react Not a pure module */
