// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TranslateService from "./TranslateService.js";

function OptionsApp(Props) {
  return React.createElement("div", {
              className: "flex flex-col h-screen"
            }, React.createElement("div", {
                  className: "navbar bg-primary text-primary-content"
                }, React.createElement("a", {
                      className: "btn btn-ghost normal-case text-xl"
                    }, "Love Word")), React.createElement("div", {
                  className: "flex flex-1"
                }, React.createElement("ul", {
                      className: "menu bg-base-100 w-56 p-2 border-r text-base"
                    }, React.createElement("li", undefined, React.createElement("span", {
                              className: "active"
                            }, "Translate Service")), React.createElement("div", {
                          className: "divider"
                        }), React.createElement("li", {
                          className: "menu-title"
                        }, React.createElement("span", undefined, "User")), React.createElement("li", undefined, React.createElement("a", undefined, "Favorite")), React.createElement("li", undefined, React.createElement("a", undefined, "History Query"))), React.createElement("div", {
                      className: "flex-1 p-5 bg-base-200"
                    }, React.createElement("div", {
                          className: "card w-1/3 bg-base-100 shadow-xl"
                        }, React.createElement("div", {
                              className: "card-body"
                            }, React.createElement(TranslateService.make, {}))))));
}

var make = OptionsApp;

export {
  make ,
}
/* react Not a pure module */
