// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as $$History from "./History.js";
import * as Favorite from "./Favorite.js";
import * as Shortcut from "./Shortcut.js";
import * as TranslateService from "./TranslateService.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";

function OptionsApp(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  React.useEffect((function () {
          if (url.hash === "") {
            RescriptReactRouter.push("#service");
          }
          
        }), [url]);
  var contentClass = React.useMemo((function () {
          var isRecordUrl = [
              "favorite",
              "history"
            ].includes(url.hash);
          if (isRecordUrl) {
            return "";
          } else {
            return "p-5";
          }
        }), [url.hash]);
  var match = url.hash === "service";
  var match$1 = url.hash === "shortcut";
  var match$2 = url.hash === "favorite";
  var match$3 = url.hash === "history";
  var match$4 = url.hash;
  var tmp;
  switch (match$4) {
    case "favorite" :
        tmp = React.createElement(Favorite.make, {});
        break;
    case "history" :
        tmp = React.createElement($$History.make, {});
        break;
    case "service" :
        tmp = React.createElement(TranslateService.make, {});
        break;
    case "shortcut" :
        tmp = React.createElement(Shortcut.make, {});
        break;
    default:
      tmp = "Page Not Found";
  }
  return React.createElement("div", {
              className: "flex flex-col h-screen text-base"
            }, React.createElement("div", {
                  className: "navbar bg-primary text-primary-content"
                }, React.createElement("a", {
                      className: "btn btn-ghost normal-case text-xl",
                      href: "#service"
                    }, "Love Word")), React.createElement("div", {
                  className: "flex flex-1 overflow-y-hidden"
                }, React.createElement("div", {
                      className: "overflow-y-auto"
                    }, React.createElement("ul", {
                          className: "menu bg-base-100 w-56 p-2 border-r"
                        }, React.createElement("li", {
                              className: "menu-title"
                            }, React.createElement("span", undefined, "Setting")), React.createElement("li", undefined, React.createElement("a", {
                                  className: match ? "active" : "",
                                  href: "#service"
                                }, "Translate Service")), React.createElement("li", undefined, React.createElement("a", {
                                  className: match$1 ? "active" : "",
                                  href: "#shortcut"
                                }, "Shortcut")), React.createElement("div", {
                              className: "divider"
                            }), React.createElement("li", {
                              className: "menu-title"
                            }, React.createElement("span", undefined, "User")), React.createElement("li", undefined, React.createElement("a", {
                                  className: match$2 ? "active" : "",
                                  href: "#favorite"
                                }, "Favorite")), React.createElement("li", undefined, React.createElement("a", {
                                  className: match$3 ? "active" : "",
                                  href: "#history"
                                }, "History Query")))), React.createElement("div", {
                      className: "flex-1 overflow-y-auto bg-base-200 " + contentClass + ""
                    }, tmp)));
}

var make = OptionsApp;

export {
  make ,
}
/* react Not a pure module */
