// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OptionsApp from "./OptionsApp.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import '../common.css'
;

var rootElement = document.querySelector("#root");

if (!(rootElement == null)) {
  var root = Client.createRoot(rootElement);
  root.render(JsxRuntime.jsx(OptionsApp.make, {}));
}

export {
  
}
/*  Not a pure module */
