// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as OptionsApp from "./OptionsApp.js";
import * as Client from "react-dom/client";

import '../common.css'
;

var rootElement = document.querySelector("#root");

if (!(rootElement == null)) {
  var root = Client.createRoot(rootElement);
  root.render(React.createElement(OptionsApp.make, {}));
}

export {
  
}
/*  Not a pure module */
