// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as OptionsApp from "./OptionsApp.js";

import '../common.css'
;

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(OptionsApp.make, {}), root);
}

export {
  
}
/*  Not a pure module */
