// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Login from "./Login.js";
import * as React from "react";
import * as $$History from "./History.js";
import * as Favorite from "./Favorite.js";
import * as Shortcut from "./Shortcut.js";
import * as TranslateService from "./TranslateService.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";

function OptionsApp(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = React.useState(function () {
        return "UnLogined";
      });
  var setUser = match[1];
  var user = match[0];
  React.useEffect((function () {
          var getUser = async function () {
            var result = await chrome.storage.local.get(["user"]);
            var u = result.user;
            return setUser(function (param) {
                        return u;
                      });
          };
          getUser(undefined);
        }), []);
  React.useEffect((function () {
          if (url.hash === "") {
            RescriptReactRouter.push("#service");
          }
          
        }), [url]);
  var contentClass = React.useMemo((function () {
          var isRecordUrl = [
              "favorite",
              "history"
            ].includes(url.hash);
          if (isRecordUrl) {
            return "";
          } else {
            return "p-5";
          }
        }), [url.hash]);
  var logout = function (param) {
    chrome.storage.local.remove(["user"]);
    setUser(function (param) {
          return "UnLogined";
        });
  };
  var tmp;
  tmp = typeof user !== "object" ? "" : user.profileImage;
  var hasLoginedComponent = React.createElement("div", {
        className: "dropdown dropdown-end"
      }, React.createElement("label", {
            className: "btn btn-ghost btn-circle avatar",
            tabIndex: 0
          }, React.createElement("div", {
                className: "w-10 rounded-full"
              }, React.createElement("img", {
                    src: tmp
                  }))), React.createElement("ul", {
            className: "mt-3 z-[99] p-2 shadow menu menu-compact dropdown-content bg-base-100 border border-slate-500 rounded-box w-52",
            tabIndex: 1
          }, React.createElement("li", undefined, React.createElement("a", {
                    className: "justify-between"
                  }, "Profile")), React.createElement("li", {
                onClick: logout
              }, React.createElement("a", undefined, "Logout"))));
  var loginStatus;
  loginStatus = typeof user !== "object" ? React.createElement("button", {
          className: "btn",
          onClick: (function (param) {
              window.login.showModal();
            })
        }, "Login") : hasLoginedComponent;
  var match$1 = url.hash === "service";
  var match$2 = url.hash === "shortcut";
  var match$3 = url.hash === "favorite";
  var match$4 = url.hash === "history";
  var match$5 = url.hash;
  var tmp$1;
  switch (match$5) {
    case "favorite" :
        tmp$1 = React.createElement(Favorite.make, {});
        break;
    case "history" :
        tmp$1 = React.createElement($$History.make, {});
        break;
    case "service" :
        tmp$1 = React.createElement(TranslateService.make, {});
        break;
    case "shortcut" :
        tmp$1 = React.createElement(Shortcut.make, {});
        break;
    default:
      tmp$1 = "Page Not Found";
  }
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "flex flex-col h-screen"
                }, React.createElement("div", {
                      className: "navbar bg-base-100 border-b-2"
                    }, React.createElement("div", {
                          className: "flex-1"
                        }, React.createElement("a", {
                              className: "btn btn-ghost normal-case text-xl",
                              href: "#service"
                            }, React.createElement("img", {
                                  className: " inline-block mr-2",
                                  src: "/icons/lw32x32.png"
                                }), "Love Word")), React.createElement("div", {
                          className: "flex-none gap-2"
                        }, loginStatus), React.createElement("dialog", {
                          className: "modal",
                          id: "login"
                        }, React.createElement("form", {
                              className: "modal-box",
                              method: "dialog"
                            }, React.createElement(Login.make, {
                                  onSubmit: (function (u) {
                                      setUser(u);
                                      window.login.close();
                                    }),
                                  onCancel: (function () {
                                      window.login.close();
                                    })
                                })))), React.createElement("div", {
                      className: "flex flex-1 overflow-y-hidden"
                    }, React.createElement("div", {
                          className: "overflow-y-auto border-r-2"
                        }, React.createElement("ul", {
                              className: "menu bg-base-100 w-56 p-2"
                            }, React.createElement("li", {
                                  className: "menu-title"
                                }, React.createElement("span", undefined, "Setting")), React.createElement("li", undefined, React.createElement("a", {
                                      className: match$1 ? "active" : "",
                                      href: "#service"
                                    }, "Translate Service")), React.createElement("li", undefined, React.createElement("a", {
                                      className: match$2 ? "active" : "",
                                      href: "#shortcut"
                                    }, "Shortcut")), React.createElement("div", {
                                  className: "divider"
                                }), React.createElement("li", {
                                  className: "menu-title"
                                }, React.createElement("span", undefined, "User")), React.createElement("li", undefined, React.createElement("a", {
                                      className: match$3 ? "active" : "",
                                      href: "#favorite"
                                    }, "Favorite")), React.createElement("li", undefined, React.createElement("a", {
                                      className: match$4 ? "active" : "",
                                      href: "#history"
                                    }, "History Query")))), React.createElement("div", {
                          className: "flex-1 overflow-y-auto bg-base-200 " + contentClass
                        }, tmp$1))));
}

var make = OptionsApp;

export {
  make ,
}
/* Login Not a pure module */
