// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function RecordAction(props) {
  var onCancel = props.onCancel;
  var onSearch = props.onSearch;
  var onClear = props.onClear;
  var onSync = props.onSync;
  var onDelete = props.onDelete;
  var records = props.records;
  var records$1 = records !== undefined ? records : [];
  var match = React.useState(function () {
        return "None";
      });
  var setBtnState = match[1];
  var btnState = match[0];
  var checkedLen = records$1.length;
  var onClick = function (param) {
    switch (btnState) {
      case "DELETE" :
          return onDelete(records$1);
      case "SYNC" :
          return onSync(records$1);
      case "CLEAR" :
          return onClear(undefined);
      case "None" :
          return ;
      
    }
  };
  return React.createElement("div", {
              className: "sticky top-0 z-40 bg-base-100 p-4 border-b-2"
            }, React.createElement("dialog", {
                  className: "modal",
                  id: "recordAction"
                }, React.createElement("form", {
                      className: "modal-box",
                      method: "dialog"
                    }, React.createElement("h3", {
                          className: "font-bold text-lg"
                        }, "Do you confirm?"), React.createElement("div", {
                          className: "modal-action"
                        }, React.createElement("button", {
                              className: "btn btn-error",
                              onClick: onClick
                            }, "Confirm"), React.createElement("button", {
                              className: "btn"
                            }, "Cancel")))), React.createElement("div", {
                  className: "flex gap-5 items-center"
                }, React.createElement("input", {
                      className: "input input-primary w-full max-w-xs",
                      placeholder: "Search...",
                      type: "text",
                      onChange: (function (e) {
                          onSearch(e.target.value);
                        })
                    }), checkedLen > 0 ? React.createElement("div", {
                        className: "join"
                      }, React.createElement("button", {
                            className: "btn btn-warning join-item",
                            onClick: (function (param) {
                                setBtnState(function (param) {
                                      return "DELETE";
                                    });
                                window.recordAction.showModal();
                              })
                          }, React.createElement("span", undefined, "Delete"), React.createElement("span", undefined, "(" + checkedLen.toString() + ")")), React.createElement("button", {
                            className: "btn btn-secondary join-item",
                            onClick: (function (param) {
                                setBtnState(function (param) {
                                      return "SYNC";
                                    });
                                window.recordAction.showModal();
                              })
                          }, React.createElement("span", undefined, "Sync"), React.createElement("span", undefined, "(" + checkedLen.toString() + ")")), React.createElement("button", {
                            className: "btn btn-error join-item",
                            onClick: (function (param) {
                                setBtnState(function (param) {
                                      return "CLEAR";
                                    });
                                window.recordAction.showModal();
                              })
                          }, "Clear"), React.createElement("button", {
                            className: "btn join-item",
                            onClick: (function (param) {
                                onCancel(undefined);
                              })
                          }, "Cancel")) : null));
}

var make = RecordAction;

export {
  make ,
}
/* react Not a pure module */
