// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Shortcut(Props) {
  return React.createElement("div", {
              className: "card card-compact w-40 bg-base-100 shadow-xl"
            }, React.createElement("div", {
                  className: "card-body"
                }, React.createElement("div", {
                      className: "bg-base-100 font-bold"
                    }, "Assist key"), React.createElement("div", {
                      className: "form-control"
                    }, React.createElement("label", {
                          className: "label cursor-pointer"
                        }, React.createElement("span", {
                              className: "label-text"
                            }, "ALT"), React.createElement("input", {
                              className: "checkbox checkbox-primary",
                              checked: true,
                              type: "checkbox"
                            })))));
}

var make = Shortcut;

export {
  make ,
}
/* react Not a pure module */
