// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Shortcut(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                            children: "Assist key",
                            className: "bg-base-100 font-bold"
                          }),
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsxs("label", {
                                  children: [
                                    JsxRuntime.jsx("span", {
                                          children: "ALT",
                                          className: "label-text"
                                        }),
                                    JsxRuntime.jsx("input", {
                                          defaultChecked: true,
                                          className: "checkbox",
                                          type: "checkbox"
                                        })
                                  ],
                                  className: "label cursor-pointer"
                                }),
                            className: "form-control"
                          })
                    ],
                    className: "card-body"
                  }),
              className: "card card-compact w-40 bg-base-100 shadow-xl"
            });
}

var make = Shortcut;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
