// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Widget from "../components/Widget.js";
import * as TranSource from "../TranSource.js";
import * as JsxRuntime from "react/jsx-runtime";

function TranslateService(props) {
  var match = React.useState(function () {
        return "";
      });
  var setAppid = match[1];
  var appid = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setSecret = match$1[1];
  var secret = match$1[0];
  var match$2 = React.useState(function () {
        return true;
      });
  var setDisabled = match$2[1];
  var match$3 = React.useState(function () {
        return true;
      });
  var setPasswordVisible = match$3[1];
  var passwordVisible = match$3[0];
  var match$4 = React.useState(function () {
        return "";
      });
  var setWarnMessage = match$4[1];
  var warnMessage = match$4[0];
  React.useEffect((function () {
          var fetchBaiduKey = async function () {
            var result = await chrome.storage.local.get(["baiduKey"]);
            var config = result.baiduKey;
            if (!(config == null)) {
              setAppid(function (param) {
                    return config.appid;
                  });
              return setSecret(function (param) {
                          return config.secret;
                        });
            }
            
          };
          fetchBaiduKey();
        }), []);
  var handleSubmit = async function () {
    var config = {
      appid: appid,
      secret: secret
    };
    chrome.storage.local.set({
          baiduKey: config
        });
    var br = await TranSource.Baidu.translate("hello world");
    if (br.TAG === "Ok") {
      await chrome.storage.local.set({
            baiduKey: config
          });
      setWarnMessage(function (param) {
            return "";
          });
      return setDisabled(function (param) {
                  return true;
                });
    }
    var msg = br._0;
    await chrome.storage.local.remove(["baiduKey"]);
    setWarnMessage(function (param) {
          return msg;
        });
    return setDisabled(function (param) {
                return false;
              });
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("label", {
                                    children: JsxRuntime.jsx("span", {
                                          children: "baidu appid",
                                          className: "label-text"
                                        }),
                                    className: "label"
                                  }),
                              JsxRuntime.jsx("input", {
                                    className: "input input-bordered w-full",
                                    placeholder: "Appid",
                                    type: "text",
                                    value: appid,
                                    onChange: (function (e) {
                                        setAppid(function (param) {
                                              return e.target.value;
                                            });
                                        setDisabled(function (param) {
                                              return false;
                                            });
                                      })
                                  })
                            ],
                            className: "form-control "
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("label", {
                                    children: JsxRuntime.jsx("span", {
                                          children: "baidu secret",
                                          className: "label-text"
                                        }),
                                    className: "label"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("input", {
                                            className: "input input-bordered w-full pr-8",
                                            placeholder: "Secret",
                                            type: passwordVisible ? "password" : "text",
                                            value: secret,
                                            onChange: (function (e) {
                                                setSecret(function (param) {
                                                      return e.target.value;
                                                    });
                                                setDisabled(function (param) {
                                                      return false;
                                                    });
                                              })
                                          }),
                                      JsxRuntime.jsx("span", {
                                            children: passwordVisible ? JsxRuntime.jsx(Widget.EyeSlash.make, {}) : JsxRuntime.jsx(Widget.Eye.make, {}),
                                            className: "cursor-pointer absolute w-6 h-6 top-1/2 right-1.5 -translate-y-1/2",
                                            onClick: (function (param) {
                                                setPasswordVisible(function (_p) {
                                                      return !passwordVisible;
                                                    });
                                              })
                                          })
                                    ],
                                    className: "relative"
                                  })
                            ],
                            className: "form-control mt-5"
                          }),
                      warnMessage !== "" ? JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx(Widget.Alert.make, {}),
                                      JsxRuntime.jsx("span", {
                                            children: "Warning: " + warnMessage + "!"
                                          })
                                    ]
                                  }),
                              className: "alert alert-warning shadow-lg mt-5"
                            }) : null,
                      JsxRuntime.jsx("button", {
                            children: "Submit",
                            className: "btn btn-neutral " + (
                              match$2[0] ? "btn-disabled" : ""
                            ) + " w-5/6 mt-8 mx-auto",
                            onClick: (function (param) {
                                handleSubmit();
                              })
                          })
                    ],
                    className: "card-body"
                  }),
              className: "card w-1/3 bg-base-100 shadow-xl"
            });
}

var make = TranslateService;

export {
  make ,
}
/* react Not a pure module */
