// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../Utils.js";
import * as React from "react";
import * as Widget from "../components/Widget.js";

function TranslateService(props) {
  var match = React.useState(function () {
        return "";
      });
  var setAppid = match[1];
  var appid = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setSecret = match$1[1];
  var secret = match$1[0];
  var match$2 = React.useState(function () {
        return "";
      });
  var setWarnMessage = match$2[1];
  var warnMessage = match$2[0];
  React.useEffect((function () {
          var fetchBaiduKey = async function (param) {
            var result = await chrome.storage.local.get(["baiduKey"]);
            var config = result.baiduKey;
            if (!(config == null)) {
              setAppid(function (param) {
                    return config.appid;
                  });
              return setSecret(function (param) {
                          return config.secret;
                        });
            }
            
          };
          fetchBaiduKey(undefined);
        }), []);
  var handleSubmit = async function (param) {
    var config = {
      appid: appid,
      secret: secret
    };
    chrome.storage.local.set({
          baiduKey: config
        });
    var br = await Utils.Baidu.translate("hello world");
    if (br.TAG === /* Ok */0) {
      await chrome.storage.local.set({
            baiduKey: config
          });
      return setWarnMessage(function (param) {
                  return "";
                });
    }
    var msg = br._0;
    await chrome.storage.local.remove(["baiduKey"]);
    return setWarnMessage(function (param) {
                return msg;
              });
  };
  return React.createElement("div", {
              className: "card w-1/3 bg-base-100 shadow-xl"
            }, React.createElement("div", {
                  className: "card-body"
                }, React.createElement("div", {
                      className: "form-control "
                    }, React.createElement("label", {
                          className: "label"
                        }, React.createElement("span", {
                              className: "label-text"
                            }, "baidu appid")), React.createElement("input", {
                          className: "input input-bordered input-primary w-full",
                          placeholder: "Appid",
                          type: "text",
                          value: appid,
                          onChange: (function (e) {
                              setAppid(function (param) {
                                    return e.target.value;
                                  });
                            })
                        })), React.createElement("div", {
                      className: "form-control mt-5"
                    }, React.createElement("label", {
                          className: "label"
                        }, React.createElement("span", {
                              className: "label-text"
                            }, "baidu secret")), React.createElement("input", {
                          className: "input input-bordered input-primary w-full",
                          placeholder: "Secret",
                          type: "text",
                          value: secret,
                          onChange: (function (e) {
                              setSecret(function (param) {
                                    return e.target.value;
                                  });
                            })
                        })), warnMessage !== "" ? React.createElement("div", {
                        className: "alert alert-warning shadow-lg mt-5"
                      }, React.createElement("div", undefined, React.createElement(Widget.Alert.make, {}), React.createElement("span", undefined, "Warning: " + warnMessage + "!"))) : null, React.createElement("button", {
                      className: "btn btn-primary w-5/6 mt-8 mx-auto",
                      onClick: (function (param) {
                          handleSubmit(undefined);
                        })
                    }, "Submit")));
}

var make = TranslateService;

export {
  make ,
}
/* Utils Not a pure module */
