// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as PopupApp from "../src/popup/PopupApp.js";
import * as TestBinding from "./utils/TestBinding.js";
import * as React$1 from "@testing-library/react";

describe("popup page", (function () {
        test("render correctly", (function () {
                TestBinding.ReactTestingLibrary.render(React.createElement(PopupApp.make, {}), undefined, undefined, undefined, undefined, undefined);
                var jumpBtn = React$1.screen.getByTitle("jump", undefined);
                var settingBtn = React$1.screen.getByTitle("setting", undefined);
                expect(jumpBtn).toBeInTheDocument();
                expect(settingBtn).toBeInTheDocument();
              }));
      }));

export {
  
}
/*  Not a pure module */
