// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../src/Utils.js";
import * as Vitest from "vitest";

Vitest.vi.stubGlobal("chrome", {
      storage: {
        local: {
          get: (function () {
              return "";
            })
        }
      }
    });

Vitest.describe("Utils Lib", (function () {
        Vitest.test("fetchByHttp is ok", (async function () {
                var res = await Utils.Lib.fetchByHttp("/dict?q=hello", undefined, undefined);
                if (res.TAG === "Ok") {
                  Vitest.expect(res._0.word).toBe("hello");
                  return ;
                }
                Vitest.expect(res._0).toBe("error");
              }));
        Vitest.test("Baidu translate is ok", (async function () {
                var val = await Utils.Baidu.translate("hello");
                if (val.TAG === "Ok") {
                  Vitest.expect(val._0).toBe("hello");
                  return ;
                }
                Vitest.expect(val._0).toBe("No translation key");
              }));
      }));

export {
  
}
/*  Not a pure module */
