// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../src/Utils.js";
import * as Fixture from "./utils/Fixture.js";

var mockChromeStore = {
  user: "iron",
  baiduKey: {
    appid: "testAppid",
    secret: "testSecret"
  }
};

Fixture.chromeGetStoreSpy.mockResolvedValue(mockChromeStore);

describe("Utils module", (function () {
        test.each([
                "favorite",
                "history"
              ])("recordRemoteAction works %s", (async function (recordType) {
                var ret = Fixture.createMockHttpResponse(undefined, undefined, Fixture.dictData);
                Fixture.fetchSpy.mockResolvedValue(ret);
                var res = await Utils.recordRemoteAction(recordType, undefined, undefined);
                expect(res).toStrictEqual({
                      TAG: "Ok",
                      _0: Fixture.dictData
                    });
              }));
        test("recordRemoteAction works with error", (async function () {
                Fixture.chromeGetStoreSpy.mockReturnValue({
                      user: undefined
                    });
                var res = await Utils.recordRemoteAction("favorite", undefined, undefined);
                expect(res).toStrictEqual({
                      TAG: "Error",
                      _0: "nothing"
                    });
                Fixture.chromeGetStoreSpy.mockResolvedValue(mockChromeStore);
              }));
      }));

export {
  mockChromeStore ,
}
/*  Not a pure module */
