// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Widget from "../../src/components/Widget.js";
import * as TestBinding from "../utils/TestBinding.js";
import * as React$1 from "@testing-library/react";

describe("Loading widget", (function () {
        test("Loading commponent", (async function () {
                TestBinding.ReactTestingLibrary.render(React.createElement(Widget.Loading.make, {
                          delay: 150
                        }), undefined, undefined, undefined, undefined, undefined);
                var loading = await React$1.screen.findByTestId("loading", undefined);
                expect(loading).toBeInTheDocument();
              }));
      }));

export {
  
}
/*  Not a pure module */
