// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fixture from "../utils/Fixture.js";
import * as TestBinding from "../utils/TestBinding.js";
import * as MachineTPanel from "../../src/components/MachineTPanel.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as React from "@testing-library/react";
import * as UserEvent from "@testing-library/user-event";

describe("MachineTpanel component", (function () {
        test("renders correctly", (function () {
                TestBinding.ReactTestingLibrary.render(JsxRuntime.jsx(MachineTPanel.make, {
                          data: Fixture.baiduData
                        }), undefined, undefined, undefined, undefined, undefined);
                var translation = React.screen.getByText("hello", undefined);
                var playBtn = React.screen.getByRole("button", undefined);
                expect(translation).toBeInTheDocument();
                expect(playBtn).toBeInTheDocument();
              }));
        test("play button works", (async function () {
                TestBinding.ReactTestingLibrary.render(JsxRuntime.jsx(MachineTPanel.make, {
                          data: Fixture.baiduData
                        }), undefined, undefined, undefined, undefined, undefined);
                var speaker = React.screen.getByTestId("play", undefined);
                var user = UserEvent.userEvent.setup(undefined);
                await user.click(speaker);
                expect(speaker).toHaveClass("animate-fadeInOut-200ms");
                var audioElement = React.screen.getByTestId("audioPlayer", undefined);
                React.fireEvent(audioElement, new (window.Event)("ended"));
                return await React.waitFor((function () {
                              expect(speaker).not.toHaveClass("animate-fadeInOut-200ms");
                            }), undefined);
              }));
      }));

export {
  
}
/*  Not a pure module */
