// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Element = {};

var $$Document = {};

var $$MouseEvent = {};

var $$KeyboardEvent = {};

var $$Response = {};

var $$Window = {
  $$Response: $$Response
};

var Webapi = {
  $$Element: $$Element,
  $$Document: $$Document,
  $$MouseEvent: $$MouseEvent,
  $$KeyboardEvent: $$KeyboardEvent,
  $$Window: $$Window
};

var Chrome = {};

var Md5 = {};

var Qs = {};

var FrancMin = {};

var Idb = {};

export {
  Webapi ,
  Chrome ,
  Md5 ,
  Qs ,
  FrancMin ,
  Idb ,
}
/* No side effect */
