// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Element = {};

var $$Document = {};

var $$MouseEvent = {};

var $$KeyboardEvent = {};

var $$Window = {};

var Webapi = {
  $$Element: $$Element,
  $$Document: $$Document,
  $$MouseEvent: $$MouseEvent,
  $$KeyboardEvent: $$KeyboardEvent,
  $$Window: $$Window
};

var Chrome = {};

var Md5 = {};

export {
  Webapi ,
  Chrome ,
  Md5 ,
}
/* No side effect */
