// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function useTranslate(text) {
  var match = React.useState(function () {
        return false;
      });
  var setLoading = match[1];
  var match$1 = React.useState(function () {
        
      });
  var setData = match$1[1];
  React.useEffect((function () {
          var fetchTranslateResult = async function (txt) {
            if (txt === "") {
              return ;
            }
            setLoading(function (_p) {
                  return true;
                });
            var ret = await chrome.runtime.sendMessage({
                  TAG: /* TranslateMsgContent */0,
                  _0: {
                    text: txt
                  }
                });
            if (ret.TAG === /* Ok */0) {
              var val = ret._0;
              setData(function (_p) {
                    return {
                            TAG: /* Ok */0,
                            _0: val
                          };
                  });
              chrome.runtime.sendMessage({
                    TAG: /* HistoryAddMsgContent */6,
                    _0: {
                      text: txt
                    }
                  });
            } else {
              var msg = ret._0;
              setData(function (_p) {
                    return {
                            TAG: /* Error */1,
                            _0: msg
                          };
                  });
            }
            return setLoading(function (_p) {
                        return false;
                      });
          };
          fetchTranslateResult(text);
          return (function (param) {
                    setData(function (_p) {
                          
                        });
                  });
        }), [text]);
  return {
          loading: match[0],
          data: match$1[0]
        };
}

export {
  useTranslate ,
}
/* react Not a pure module */
