// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Fixture from "../utils/Fixture.js";
import * as Favorite from "../../src/options/Favorite.js";
import * as RecordHook from "../../src/hooks/RecordHook.js";
import * as TestBinding from "../utils/TestBinding.js";
import * as React$1 from "@testing-library/react";

vi.mock("../../src/hooks/RecordHook.js", undefined);

var mockUserRecordData = {
  records: [
    Fixture.dictRecord,
    Fixture.baiduRecord
  ],
  onCheck: vi.fn(undefined),
  onCancel: vi.fn(undefined),
  onClear: vi.fn(undefined),
  onDelete: vi.fn(undefined),
  onSync: vi.fn(undefined),
  onSearch: vi.fn(undefined)
};

RecordHook.useRecord.mockReturnValue(mockUserRecordData);

describe("History in options page", (function () {
        test("render correctly", (async function () {
                TestBinding.ReactTestingLibrary.render(React.createElement(Favorite.make, {}), undefined, undefined, undefined, undefined, undefined);
                var transWraps = await React$1.screen.findAllByTestId("transWrap", undefined);
                expect(transWraps).toHaveLength(2);
              }));
        test.todo("check");
        test.todo("sync");
        test.todo("delete");
        test.todo("clear");
      }));

export {
  mockUserRecordData ,
}
/*  Not a pure module */
