// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fixture from "../utils/Fixture.js";
import * as $$History from "../../src/options/History.js";
import * as RecordHook from "../../src/hooks/RecordHook.js";
import * as TestBinding from "../utils/TestBinding.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as React from "@testing-library/react";

vi.mock("../../src/hooks/RecordHook.js", undefined);

var mockUserRecordData = {
  records: [
    Fixture.dictRecord,
    Fixture.baiduRecord
  ],
  onCheck: vi.fn(undefined),
  onCancel: vi.fn(undefined),
  onClear: vi.fn(undefined),
  onDelete: vi.fn(undefined),
  onSync: vi.fn(undefined),
  onSearch: vi.fn(undefined)
};

RecordHook.useRecord.mockReturnValue(mockUserRecordData);

describe("History in options page", (function () {
        test("render correctly", (async function () {
                TestBinding.ReactTestingLibrary.render(JsxRuntime.jsx($$History.make, {}), undefined, undefined, undefined, undefined, undefined);
                var transWraps = await React.screen.findAllByTestId("historyItemWrap", undefined);
                expect(transWraps).toHaveLength(2);
              }));
        test.todo("abcd");
      }));

export {
  mockUserRecordData ,
}
/*  Not a pure module */
