// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Login from "../../src/options/Login.js";
import * as React from "react";
import * as TestBinding from "../utils/TestBinding.js";
import * as React$1 from "@testing-library/react";

var onSubmit = vi.fn(undefined);

var onCancel = vi.fn(undefined);

describe("Login Modal", (function () {
        test("render correctly", (function () {
                TestBinding.ReactTestingLibrary.render(React.createElement(Login.make, {
                          onSubmit: onSubmit,
                          onCancel: onCancel
                        }), undefined, undefined, undefined, undefined, undefined);
                var modalTitle = React$1.screen.getByText("Login", undefined);
                expect(modalTitle).toBeInTheDocument();
              }));
        test.todo("Username");
        test.todo("Password");
        test.todo("Submit");
        test.todo("Cancel");
      }));

export {
  onSubmit ,
  onCancel ,
}
/* onSubmit Not a pure module */
