// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fixture from "../utils/Fixture.js";
import * as Shortcut from "../../src/options/Shortcut.js";
import * as OptionsApp from "../../src/options/OptionsApp.js";
import * as TestBinding from "../utils/TestBinding.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as React from "@testing-library/react";

describe("options page", (function () {
        beforeAll(function () {
              return Fixture.chromeGetStoreSpy.mockResolvedValue();
            });
        test.skip("render correctly", (function () {
                TestBinding.ReactTestingLibrary.render(JsxRuntime.jsx(OptionsApp.make, {}), undefined, undefined, undefined, undefined, undefined);
                var logoTitle = React.screen.getByText("Love Word", undefined);
                expect(logoTitle).toBeInTheDocument();
              }));
        test("Shortcut menu", (function () {
                TestBinding.ReactTestingLibrary.render(JsxRuntime.jsx(Shortcut.make, {}), undefined, undefined, undefined, undefined, undefined);
                var text = React.screen.getByText("Assist key", undefined);
                expect(text).toBeInTheDocument();
              }));
      }));

export {
  
}
/*  Not a pure module */
