// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fixture from "../utils/Fixture.js";
import * as TestBinding from "../utils/TestBinding.js";
import * as RecordAction from "../../src/options/RecordAction.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as React from "@testing-library/react";

describe("RecordAction component at options page", (function () {
        beforeEach(function () {
              TestBinding.ReactTestingLibrary.render(JsxRuntime.jsx(RecordAction.make, {
                        records: [
                          Fixture.dictRecord,
                          Fixture.baiduRecord
                        ],
                        onDelete: vi.fn(undefined),
                        onSync: vi.fn(undefined),
                        onClear: vi.fn(undefined),
                        onSearch: vi.fn(undefined),
                        onCancel: vi.fn(undefined)
                      }), undefined, undefined, undefined, undefined, undefined);
            });
        test("render correctly", (function () {
                var actionBtns = React.screen.getAllByRole("button", undefined);
                expect(actionBtns).toHaveLength(4);
              }));
      }));

export {
  
}
/*  Not a pure module */
