// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ContentApp from "./ContentApp.js";
import * as Client from "react-dom/client";

var id = "loveWord";

var host = document.createElement("div");

host.setAttribute("id", id);

host.setAttribute("style", "all: initial;");

var shadowEl = host.attachShadow({
      mode: "open"
    });

document.documentElement.appendChild(host);

var shadow = Client.createRoot(shadowEl);

shadow.render(React.createElement(ContentApp.make, {
          host: host
        }));

export {
  id ,
  host ,
  shadowEl ,
  shadow ,
}
/* host Not a pure module */
