// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as ContentApp from "./ContentApp.js";

var id = "loveWord";

var host = document.createElement("div");

host.setAttribute("id", id);

host.setAttribute("style", "all: initial;");

var shadow = host.attachShadow({
      mode: "open"
    });

document.documentElement.appendChild(host);

ReactDom.render(React.createElement(ContentApp.make, {
          host: host
        }), shadow);

export {
  id ,
  host ,
  shadow ,
}
/* host Not a pure module */
