// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ContentApp from "./ContentApp.js";
import * as Client from "react-dom/client";
import CommonCssinline from "../common.css?inline";

var commonCss = CommonCssinline;

var id = "__loveWord__";

var host = document.createElement("div");

host.setAttribute("id", id);

host.setAttribute("style", "all: initial;");

var shadowEl = host.attachShadow({
      mode: "open"
    });

document.documentElement.appendChild(host);

var shadow = Client.createRoot(shadowEl);

shadow.render(React.createElement(React.Fragment, undefined, React.createElement("style", undefined, commonCss), React.createElement(ContentApp.make, {
              host: host
            })));

export {
  commonCss ,
  id ,
  host ,
  shadowEl ,
  shadow ,
}
/* commonCss Not a pure module */
