// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Widget from "./Widget.js";

function FavButton(props) {
  var trans = props.trans;
  var text = props.text;
  var match = React.useState(function () {
        return false;
      });
  var setFaved = match[1];
  var isFaved = match[0];
  var favAction = async function (action) {
    var msgContent;
    switch (action) {
      case "Get" :
          msgContent = {
            TAG: "FavGetOneMsgContent",
            _0: {
              text: text
            }
          };
          break;
      case "Add" :
          msgContent = {
            TAG: "FavAddMsgContent",
            _0: {
              text: text,
              translation: trans
            }
          };
          break;
      case "Delete" :
          msgContent = {
            TAG: "FavDeleteOneMsgContent",
            _0: {
              text: text
            }
          };
          break;
      
    }
    if (text === "") {
      return ;
    }
    var faved = await chrome.runtime.sendMessage(msgContent);
    return setFaved(function (param) {
                return faved;
              });
  };
  React.useEffect((function () {
          favAction("Get");
        }), [text]);
  return React.createElement("button", {
              className: "btn btn-xs w-5 h-5 min-h-0 btn-circle btn-ghost",
              onClick: (function (param) {
                  favAction(isFaved ? "Delete" : "Add");
                })
            }, isFaved ? React.createElement(Widget.StarFill.make, {}) : React.createElement(Widget.Star.make, {}));
}

var make = FavButton;

export {
  make ,
}
/* react Not a pure module */
