// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Widget from "./Widget.js";

function FavButton(props) {
  var trans = props.trans;
  var text = props.text;
  var match = React.useState(function () {
        return false;
      });
  var setFaved = match[1];
  var isFaved = match[0];
  var favAction = function (action) {
    if (text !== "") {
      chrome.runtime.sendMessage({
              _type: /* Message */{
                _0: /* FAVORITE */1,
                _1: action
              },
              text: text,
              trans: trans
            }).then(function (faved) {
            setFaved(function (param) {
                  return faved;
                });
            return Promise.resolve(undefined);
          });
      return ;
    }
    
  };
  React.useEffect((function () {
          favAction(/* GET */1);
        }), [text]);
  return React.createElement("button", {
              className: "btn btn-xs w-5 h-5 fill-white min-h-0 btn-circle btn-ghost",
              onClick: (function (param) {
                  favAction(isFaved ? /* DELETE */3 : /* ADD */0);
                })
            }, isFaved ? React.createElement(Widget.StarFill.make, {}) : React.createElement(Widget.Star.make, {}));
}

var make = FavButton;

export {
  make ,
}
/* react Not a pure module */
