// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Loading(Props) {
  return React.createElement("div", undefined, "loading...");
}

var make = Loading;

export {
  make ,
}
/* react Not a pure module */
