// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Loading from "./Loading.js";
import * as DictPanel from "./DictPanel.js";
import * as FrancMin from "franc-min";
import * as MachineTPanel from "./MachineTPanel.js";
import * as TranslateHook from "../hooks/TranslateHook.js";

function TranslateResult(Props) {
  var q = Props.q;
  var className = Props.className;
  var match = TranslateHook.useTranslate(q);
  var errText = match.errText;
  var tmp;
  switch (match.loading) {
    case /* Yes */0 :
        tmp = React.createElement(Loading.make, {});
        break;
    case /* No */1 :
        if (errText !== "") {
          tmp = React.createElement("div", undefined, errText);
        } else {
          var sl = FrancMin.franc(q, {
                minLength: 1,
                only: [
                  "eng",
                  "cmn"
                ]
              });
          var len = q.split(" ");
          tmp = len.length === 1 && sl === "eng" ? React.createElement(DictPanel.make, {}) : React.createElement(MachineTPanel.make, {
                  results: match.results
                });
        }
        break;
    case /* Noop */2 :
        tmp = null;
        break;
    
  }
  return React.createElement("div", {
              className: "" + className + " lw-scroll-wrap max-h-52 overflow-y-auto overscroll-contain"
            }, tmp);
}

var make = TranslateResult;

export {
  make ,
}
/* react Not a pure module */
