// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Widget from "./Widget.js";
import * as DictPanel from "./DictPanel.js";
import * as MachineTPanel from "./MachineTPanel.js";

function TranslateResult(props) {
  var className = props.className;
  var errText = props.errText;
  var data = props.data;
  var loading = props.loading;
  var loading$1 = loading !== undefined ? loading : /* No */1;
  var errText$1 = errText !== undefined ? errText : "";
  var className$1 = className !== undefined ? className : "";
  var spanning = loading$1 === 0;
  var tmp;
  if (errText$1 !== "") {
    tmp = React.createElement("div", {
          className: "text-error"
        }, errText$1);
  } else {
    switch (data.TAG | 0) {
      case /* DictT */0 :
          tmp = React.createElement(DictPanel.make, {
                data: data.dict
              });
          break;
      case /* BaiduT */1 :
          tmp = React.createElement(MachineTPanel.make, {
                data: data.baidu
              });
          break;
      case /* Message */2 :
          tmp = null;
          break;
      
    }
  }
  return React.createElement("div", {
              className: "" + className$1 + " lw-scroll-wrap max-h-52 overflow-y-auto overscroll-contain"
            }, React.createElement(Widget.Loading.make, {
                  loading: spanning,
                  delay: 450,
                  children: tmp
                }));
}

var make = TranslateResult;

export {
  make ,
}
/* react Not a pure module */
