// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Widget$Loading(Props) {
  return React.createElement("div", undefined, "loading...");
}

var Loading = {
  make: Widget$Loading
};

function Widget$Tag(Props) {
  var classNameOpt = Props.className;
  var children = Props.children;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("span", {
              className: "rounded-sm inline-block px-1 " + className + ""
            }, children);
}

var Tag = {
  make: Widget$Tag
};

export {
  Loading ,
  Tag ,
}
/* react Not a pure module */
