// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./utils.js";

chrome.runtime.onMessage.addListener(function (message, param, sendResponse) {
      Utils.adapterTrans(message).then(function (ret) {
            return sendResponse(ret);
          });
      return true;
    });

export {
  
}
/*  Not a pure module */
