// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./utils.js";

chrome.runtime.onMessage.addListener(function (message, param, sendResponse) {
      Utils.Baidu.translate(message).then(function (res) {
            return sendResponse(res);
          });
      return true;
    });

export {
  
}
/*  Not a pure module */
