// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Idb from "idb";

function getDB(param) {
  return Idb.openDB("loveWord", undefined, {
              upgrade: (function (db) {
                  var favoriteStore = db.createObjectStore("favorite", {
                        keyPath: "date"
                      });
                  favoriteStore.createIndex("date", "date");
                  favoriteStore.createIndex("text", "text");
                  var historyStore = db.createObjectStore("history", {
                        keyPath: "date"
                      });
                  historyStore.createIndex("date", "date");
                })
            });
}

export {
  getDB ,
}
/* idb Not a pure module */
