// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Idb from "idb";

function createStoreWithIndex(db, storeName) {
  var favoriteStore = db.createObjectStore(storeName, {
        keyPath: "date"
      });
  favoriteStore.createIndex("date", "date");
  favoriteStore.createIndex("text", "text");
}

async function getDB() {
  return await Idb.openDB("loveWord", undefined, {
              upgrade: (function (db) {
                  createStoreWithIndex(db, "favorite");
                  createStoreWithIndex(db, "history");
                })
            });
}

export {
  createStoreWithIndex ,
  getDB ,
}
/* idb Not a pure module */
