// Generated by ReScript, PLEASE EDIT WITH CARE

import Md5 from "md5";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

var endpoint = "https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=zh-Hans&dt=t";

function translateByGoogle(msg) {
  return fetch("" + endpoint + "&q=" + msg + "", undefined).then(function (ret) {
                return ret.json();
              }).then(function (result) {
              var tmp;
              if (Array.isArray(result)) {
                var fl = result[0];
                if (Array.isArray(fl)) {
                  var sl = fl[0];
                  tmp = Array.isArray(sl) ? sl[0] : undefined;
                } else {
                  tmp = undefined;
                }
              } else {
                tmp = undefined;
              }
              return Promise.resolve(tmp);
            });
}

var Google = {
  endpoint: endpoint,
  translateByGoogle: translateByGoogle
};

var endpoint$1 = "https://api.fanyi.baidu.com/api/trans/vip/translate";

function translate(q) {
  return chrome.storage.local.get(["baiduKey"]).then(function (result) {
                    var appid = result.baiduKey.appid;
                    var key = result.baiduKey.secret;
                    var salt = Date.now().toString();
                    var sign = Md5(appid + q + salt + key);
                    return "" + endpoint$1 + "?q=" + q + "&from=auto&to=zh&appid=" + appid + "&salt=" + salt + "&sign=" + sign + "";
                  }).then(function (ret) {
                  return fetch(ret, undefined);
                }).then(function (res) {
                return res.json();
              }).then(function (result) {
              return Caml_array.get(result.trans_result, 0).dst;
            });
}

var Baidu = {
  endpoint: endpoint$1,
  translate: translate
};

export {
  Google ,
  Baidu ,
}
/* md5 Not a pure module */
