// Generated by ReScript, PLEASE EDIT WITH CARE

import Md5 from "md5";
import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

var endpoint = "https://api.fanyi.baidu.com/api/trans/vip/translate";

function translate(q) {
  return $$Promise.$$catch(chrome.storage.local.get(["baiduKey"]).then(function (result) {
                        var appid = result.baiduKey.appid;
                        var key = result.baiduKey.secret;
                        var salt = Date.now().toString();
                        var sign = Md5(appid + q + salt + key);
                        return "" + endpoint + "?q=" + q + "&from=auto&to=zh&appid=" + appid + "&salt=" + salt + "&sign=" + sign + "";
                      }).then(function (ret) {
                      return fetch(ret, undefined);
                    }).then(function (res) {
                    return res.json();
                  }).then(function (data) {
                  var msg = data.error_msg;
                  var tmp;
                  if (msg !== undefined) {
                    tmp = {
                      TAG: /* Error */1,
                      _0: msg
                    };
                  } else {
                    var trans_result = data.trans_result;
                    tmp = trans_result !== undefined ? ({
                          TAG: /* Ok */0,
                          _0: Caml_array.get(trans_result, 0).dst
                        }) : ({
                          TAG: /* Error */1,
                          _0: "No Tralation"
                        });
                  }
                  return Promise.resolve(tmp);
                }), (function (e) {
                var msg;
                if (e.RE_EXN_ID === $$Promise.JsError) {
                  var msg$1 = e._1.message;
                  msg = msg$1 !== undefined ? msg$1 : "";
                } else {
                  msg = "Unexpected error occurred";
                }
                return Promise.resolve({
                            TAG: /* Error */1,
                            _0: msg
                          });
              }));
}

var Baidu = {
  endpoint: endpoint,
  translate: translate
};

export {
  Baidu ,
}
/* md5 Not a pure module */
