// Generated by ReScript, PLEASE EDIT WITH CARE


var fetchSpy = vi.spyOn(self, "fetch");

var chromeGetStoreSpy = vi.spyOn(chrome.storage.local, "get");

var chromeSetStoreSpy = vi.spyOn(chrome.storage.local, "set");

var chromeRmStoreSpy = vi.spyOn(chrome.storage.local, "remove");

function createMockHttpResponse(codeOpt, msgOpt, data) {
  var code = codeOpt !== undefined ? codeOpt : 0;
  var msg = msgOpt !== undefined ? msgOpt : "";
  var apiBaseResponse = {
    code: code,
    data: data,
    msg: msg
  };
  return {
          json: (function () {
              return apiBaseResponse;
            })
        };
}

var baiduData = [{
    src: "你好",
    dst: "hello"
  }];

var dictData = {
  id: 1,
  word: "hello",
  translation: "interj. 喂, 嘿",
  phonetic: "hә'lәu",
  tag: "zk gk"
};

export {
  fetchSpy ,
  chromeGetStoreSpy ,
  chromeSetStoreSpy ,
  chromeRmStoreSpy ,
  createMockHttpResponse ,
  dictData ,
  baiduData ,
}
/* fetchSpy Not a pure module */
