// Generated by ReScript, PLEASE EDIT WITH CARE


var fetchSpy = vi.spyOn(self, "fetch");

var chromeGetStoreSpy = vi.spyOn(chrome.storage.local, "get");

var chromeSetStoreSpy = vi.spyOn(chrome.storage.local, "set");

var chromeRmStoreSpy = vi.spyOn(chrome.storage.local, "remove");

function createMockHttpResponse(codeOpt, msgOpt, data) {
  var code = codeOpt !== undefined ? codeOpt : 0;
  var msg = msgOpt !== undefined ? msgOpt : "";
  var apiBaseResponse = {
    code: code,
    data: data,
    msg: msg
  };
  return {
          json: (function () {
              return apiBaseResponse;
            })
        };
}

var dictData = {
  id: 1,
  word: "hello",
  translation: "interj. 喂, 嘿",
  phonetic: "hә'lәu",
  tag: "zk gk"
};

var baiduData = [{
    src: "你好",
    dst: "hello"
  }];

var baiduRecord = {
  url: "1r21.cn",
  title: "Love Word",
  favIconUrl: "",
  date: 1702484430247.0,
  text: "你好",
  translation: baiduData,
  checked: false,
  sync: false
};

var dictRecord = {
  url: "1r21.cn",
  title: "Love Word",
  favIconUrl: "",
  date: 1702484481543.0,
  text: "hello",
  translation: dictData,
  checked: false,
  sync: false
};

export {
  fetchSpy ,
  chromeGetStoreSpy ,
  chromeSetStoreSpy ,
  chromeRmStoreSpy ,
  createMockHttpResponse ,
  dictData ,
  baiduData ,
  baiduRecord ,
  dictRecord ,
}
/* fetchSpy Not a pure module */
