// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Js_undefined from "rescript/lib/es6/js_undefined.js";
import * as React from "@testing-library/react";

var Vitest = {};

function render(element, baseElement, container, hydrate, wrapper, queries) {
  var baseElement_ = container !== undefined ? Caml_option.valFromOption(container) : Js_undefined.fromOption(baseElement);
  var container_ = Js_undefined.fromOption(container);
  return React.render(element, {
              container: container_,
              baseElement: baseElement_,
              hydrate: Js_undefined.fromOption(hydrate),
              wrapper: Js_undefined.fromOption(wrapper),
              queries: Js_undefined.fromOption(queries)
            });
}

function wraperRender(element) {
  return render(element, undefined, undefined, undefined, (function (param) {
                return param.children;
              }), undefined);
}

var ReactTestingLibrary = {
  render: render,
  wraperRender: wraperRender
};

export {
  Vitest ,
  ReactTestingLibrary ,
}
/* @testing-library/react Not a pure module */
