// Generated by ReScript, PLEASE EDIT WITH CARE


self.chrome = {
  runtime: {
    sendMessage: vi.fn(undefined),
    onMessage: {
      addListener: vi.fn(undefined)
    }
  },
  storage: {
    local: {
      get: vi.fn(undefined),
      set: vi.fn(undefined),
      remove: vi.fn(undefined)
    }
  }
};

export {
  
}
/*  Not a pure module */
