// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "@testing-library/react";

import '@testing-library/jest-dom/vitest'
;

afterEach(function (prim) {
      React.cleanup();
    });

self.chrome = {
  runtime: {
    sendMessage: vi.fn(undefined),
    onMessage: {
      addListener: vi.fn(undefined)
    }
  },
  storage: {
    local: {
      get: vi.fn(undefined),
      set: vi.fn(undefined),
      remove: vi.fn(undefined)
    }
  }
};

export {
  
}
/*  Not a pure module */
